"use client";

import { useState } from "react";
import { BsStars, BsArrowRepeat } from "react-icons/bs";

interface ReviewSummaryProps {
  hotelId: string;
  hotelName: string;
}

export default function ReviewSummary({ hotelId, hotelName }: ReviewSummaryProps) {
  const [summary, setSummary] = useState<string>("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [reviewCount, setReviewCount] = useState(0);

  const generateSummary = async () => {
    try {
      setLoading(true);
      setError(null);
      setSummary(""); // Optional: clear old summary

      // 1. Fetch reviews
      const reviewsResponse = await fetch(`/api/hotels/reviews?hotelId=${hotelId}`);
      const reviewsData = await reviewsResponse.json();

      if (!reviewsResponse.ok) {
        throw new Error(reviewsData.error || "Failed to fetch reviews");
      }

      if (reviewsData.reviews.length === 0) {
        setError("No reviews available for this hotel");
        return;
      }

      setReviewCount(reviewsData.count);

      // 2. Generate AI summary
      const summaryResponse = await fetch("/api/hotels/reviews/summary", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          reviews: reviewsData.reviews,
          hotelName,
        }),
      });

      const summaryData = await summaryResponse.json();

      if (!summaryResponse.ok) {
        throw new Error(summaryData.error || "Failed to generate summary");
      }

      setSummary(summaryData.summary);
    } catch (err: any) {
      console.error("Error generating summary:", err);
      setError(err.message || "Failed to generate review summary");
    } finally {
      setLoading(false);
    }
  };

  // REMOVED: useEffect(() => generateSummary(), [hotelId])
  // → No auto-fetch on load

  return (
    <div className="bg-[#191b1d] rounded-xl shadow-md p-6 mb-8">
      <div className="flex items-center justify-between mb-4">
        <h2 className="text-2xl font-bold text-white flex items-center gap-2">
          <BsStars className="text-[#8e85e6]" />
          AI Review Summary
          <span className="text-sm font-normal text-gray-400">
            (Based on {reviewCount > 0 ? reviewCount : "?"} reviews)
          </span>
        </h2>
        <button
          onClick={generateSummary}
          disabled={loading}
          className="flex items-center gap-2 px-4 py-2 bg-[#8e85e6] hover:bg-[#7a6deb] text-white rounded-lg transition disabled:opacity-50 disabled:cursor-not-allowed"
          title="Generate AI summary"
        >
          <BsArrowRepeat className={loading ? "animate-spin" : ""} />
          <span className="hidden sm:inline">{loading ? "Analyzing..." : "Generate"}</span>
        </button>
      </div>

      {/* Only show loading when user clicks */}
      {loading && (
        <div className="flex flex-col items-center justify-center py-12 space-y-4">
          <div className="relative">
            <div className="w-16 h-16 border-4 border-[#8e85e6]/20 border-t-[#8e85e6] rounded-full animate-spin"></div>
            <BsStars className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 text-[#8e85e6] text-2xl" />
          </div>
          <p className="text-gray-400 text-center">
            Analyzing reviews with AI...
            <br />
            <span className="text-sm">This may take a few moments</span>
          </p>
        </div>
      )}

      {error && !loading && (
        <div className="bg-red-900/20 border border-red-700 rounded-lg p-4">
          <p className="text-red-400">Warning: {error}</p>
        </div>
      )}

      {summary && !loading && (
        <div className="bg-[#2a2c31] border border-gray-700 rounded-lg p-6">
          <div className="prose prose-invert max-w-none">
            <div className="text-gray-300 whitespace-pre-wrap leading-relaxed">
              {summary}
            </div>
          </div>
          <div className="mt-4 pt-4 border-t border-gray-700">
            <p className="text-xs text-gray-500 flex items-center gap-2">
              <BsStars className="text-[#8e85e6]" />
              Generated by Gemini AI • Based on recent guest reviews
            </p>
          </div>
        </div>
      )}

      {/* Initial state: no summary yet */}
      {!summary && !loading && !error && (
        <div className="text-center py-12 text-gray-500">
          <BsStars className="mx-auto text-4xl text-[#8e85e6] mb-3" />
          <p>Click "Generate" to create an AI-powered review summary</p>
        </div>
      )}
    </div>
  );
}